### ISSUE TITLE
Maybe Something Error in 'paor_data_tok_full_desc'

### ISSUE THREAD

**Issue by NTDXYG** [reddy-lab-code-research/XLCoST#1]
Hello, I download the dataset and find that there are 9265 lines in 'paor_data_tok_full_desc/train-Python-desc-tok.py' and 9263 lines in 'paor_data_tok_full_desc/train-Python-desc-tok.txt'. They don't seem to be a one-to-one match. Can you repair it?

**Comment by mingzhu0527** [comment]
Thanks for pointing it out. We have updated the data.
