### ISSUE TITLE
whitespaces in Python code files

### ISSUE THREAD

**Issue by loubnabnl** [reddy-lab-code-research/XLCoST#3]
Hi thank you for contributing this dataset, I have a question about the Python code files in the synthesis task, I was curious why you have additional whitespaces in the code for example here around parentheses and brackets:
```
def maxPresum ( a , b ) : NEW_LINE INDENT X = max ( a [ 0 ] , 0 ) 
```
Do you train the models directly on this data or do you use some preprocessing to remove the spaces and that you can point me to?
Thanks in advance!

**Comment by mingzhu0527** [comment]
The whitespace is because of tokenization. We trained the models directly on the dataset without removing the whitespaces.

**Comment by loubnabnl** [comment]
Can you elaborate more about the tokenization part, which module you used and do you know if the operation can be reversed? I also want to remove the NEWLINE, INDENT, DEDENT.. keywords to have standard python code

**Comment by loubnabnl** [comment]
BTW the text-to-code portion of the dataset is already available on Hugging Face hub in this link https://huggingface.co/datasets/codeparrot/xlcost-text-to-code if you want to mention it in the README. I can add the other subsets when I find some time otherwise  I'd be happy to assist you if you want to add it, it should be fairly similar to what we did for this portion.

**Comment by mingzhu0527** [comment]
May I ask why the dataset is listed under codeparrot?

**Comment by loubnabnl** [comment]
I just replied to your email, we can transfer the dataset to your organization once created 🙂. Would you mind answering my question about the tokenization?

**Comment by giulio98** [comment]
I also have the same question of @loubnabnl , how can I reverse the process of tokenization and get the clean code?
