### ISSUE TITLE
Mean Reciprocal Rank (MRR) for XL Code Search task

### ISSUE THREAD

**Issue by yingweima2022** [reddy-lab-code-research/XLCoST#6]
Your multilingual data set work is very solid, which is very inspiring to me. I would like to ask where is the MRR evaluation code for XL code search. It seems that it is not included in the open source code.

**Comment by aneeshjain** [comment]
The MRR evaluation can be found [here](https://github.com/reddy-lab-code-research/XLCoST/blob/main/code/codesearch/code2codesearch/evaluator/evaluator.py).
