### ISSUE TITLE
how to format the code to normal style instead of compressed in one line?

### ISSUE THREAD

**Issue by sxthunder** [reddy-lab-code-research/XLCoST#7]
First of all, thank you for the contribution on code with AI.
I wonder how to format the code to normal style instead of compressed in one line?
Are you directly train the model on the giving format? I wonder if this will make the model output code in the same style?

**Comment by aneeshjain** [comment]
Yes the model is trained on the given data format(single lines).

To get the regular formatted code you can use the language preprocessors from the `preprocessing` directory [here](https://github.com/facebookresearch/CodeGen/tree/main/codegen_sources).

An example of how to use this is the following:
```
from codegen_sources.preprocessing.lang_processors.cpp_processor import CppProcessor
from codegen_sources.preprocessing.lang_processors.python_processor import PythonProcessor
from codegen_sources.preprocessing.lang_processors.java_processor import JavaProcessor
from codegen_sources.preprocessing.lang_processors.lang_processor import LangProcessor

py_processor = LangProcessor.processors["python"](root_folder="./build")
cpp_processor = LangProcessor.processors["cpp"](root_folder="./build")
java_processor = LangProcessor.processors["java"](root_folder="./build")

py_detokenizer = py_processor.detokenize_code
cpp_detokenizer = cpp_processor.detokenize_code
java_detokenizer = java_processor.detokenize_code

processed_output = py_detokenizer("unformatted_code_string")
```

Use https://github.com/reddy-lab-code-research/XLCoST/tree/main/build for `root_folder`

**Comment by hj611** [comment]
> 是的，该模型是根据给定的数据格式（单行）进行训练的。
> 
> 要获取常规格式的代码，您可以使用[此处](https://github.com/facebookresearch/CodeGen/tree/main/codegen_sources)`preprocessing`目录中的语言修复器。[](https://github.com/facebookresearch/CodeGen/tree/main/codegen_sources)
> 
> 以下是如何使用此功能的一个示例：
> 
> ```
> from codegen_sources.preprocessing.lang_processors.cpp_processor import CppProcessor
> from codegen_sources.preprocessing.lang_processors.python_processor import PythonProcessor
> from codegen_sources.preprocessing.lang_processors.java_processor import JavaProcessor
> from codegen_sources.preprocessing.lang_processors.lang_processor import LangProcessor
> 
> py_processor = LangProcessor.processors["python"](root_folder="./build")
> cpp_processor = LangProcessor.processors["cpp"](root_folder="./build")
> java_processor = LangProcessor.processors["java"](root_folder="./build")
> 
> py_detokenizer = py_processor.detokenize_code
> cpp_detokenizer = cpp_processor.detokenize_code
> java_detokenizer = java_processor.detokenize_code
> 
> processed_output = py_detokenizer("unformatted_code_string")
> ```
> 
> 使用https://github.com/reddy-lab-code-research/XLCoST/tree/main/build[](https://github.com/reddy-lab-code-research/XLCoST/tree/main/build)`root_folder`

How should I set the "root_folder"？
